## Exercise 3. - GroupBy
###### GroupBy can be summarized as Split-Apply-Combine.
###### Check out this [Diagram](https://imgur.com/yjNkiwL).
###### Check out [Alcohol Consumption Exercises Video Tutorial](https://www.youtube.com/watch?v=az67CMdmS6s&feature=youtu.be) to watch a data scientist go through the exercises

#### Step 1. Import the necessary libraries

In [12]:
import pandas as pd

#### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [13]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv"

#### Step 3. Assign it to a variable called drinks.

In [14]:
drinks = pd.read_csv(url, sep=",")

#### Step 4. Which continent drinks more beer on average?

In [15]:
drinks.groupby('continent').agg({ 'beer_servings': 'mean' }).sort_values("beer_servings", ascending=False)

           beer_servings
continent
EU            193.777778
SA            175.083333
OC             89.687500
AF             61.471698
AS             37.045455

#### Step 5. For each continent print the statistics for wine consumption.

In [16]:
drinks.groupby('continent').agg({ 'wine_servings': 'describe' })

          wine_servings                                                   \
                  count        mean        std  min   25%    50%     75%
continent
AF                 53.0   16.264151  38.846419  0.0   1.0    2.0   13.00
AS                 44.0    9.068182  21.667034  0.0   0.0    1.0    8.00
EU                 45.0  142.222222  97.421738  0.0  59.0  128.0  195.00
OC                 16.0   35.625000  64.555790  0.0   1.0    8.5   23.25
SA                 12.0   62.416667  88.620189  1.0   3.0   12.0   98.50


             max
continent
AF         233.0
AS         123.0
EU         370.0
OC         212.0
SA         221.0

#### Step 6. Print the mean alcohol consumption per continent for every column

In [17]:
drinks.groupby('continent').mean(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

#### Step 7. Print the median alcohol consumption per continent for every column

In [20]:
drinks.groupby('continent').median(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

#### Step 8. Print the mean, min and max values for spirit consumption.
##### This time output a DataFrame

In [69]:
drinks.spirit_servings.describe()

count    193.000000
mean      80.994819
std       88.284312
min        0.000000
25%        4.000000
50%       56.000000
75%      128.000000
max      438.000000
Name: spirit_servings, dtype: float64